Ttree:
  JobButler:

    defaultAssetCollection: 'Export'
    temporaryDirectoryBase: '%FLOW_PATH_DATA%JobButler/'
    maximumExecutionTime: 300
    memoryLimit: -1

    allowedActionRedirect:
      'execute': 'forward'
      'history': 'forward'
      'schedule': 'forward'
      'configurationWizard': 'redirect'

    jobSettings:
      '*':
        'tags':
          'all': TRUE

TYPO3:

  Flow:
    security:
      authentication:
        providers:
          Typo3BackendProvider:
            requestPatterns:
              controllerObjectName: 'TYPO3\Neos\Controller\.*|TYPO3\Neos\Service\.*|TYPO3\Media\Controller\.*|Ttree\JobButler\Controller\Module\Management\.*'

  Neos:

    userInterface:

      translation:
        autoInclude:
          'Ttree.JobButler': ['Modules']

    modules:

      management:
        submodules:
          jobsbutler:
            label: 'Ttree.JobButler:Modules:jobbutler.label'
            controller: '\Ttree\JobButler\Controller\Module\Management\JobController'
            description: 'Ttree.JobButler:Modules:jobbutler.description'
            icon: 'icon-tasks'
            privilegeTarget: 'Ttree.JobButler:ExecuteJobs'
